name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repository
        uses: actions/checkout@v2

      - name: Checkout app repository
        uses: actions/checkout@v2
        with:
          repository: jaktestowac/gad-gui-api-demo
          path: app

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for app
        run: npm install
        working-directory: ./app

      - name: Build the app
        run: npm start &
        working-directory: ./app
        env:
          CI: true

      - name: Wait for the app to be ready
        run: sleep 20

      - name: Install dependencies for tests
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test
